image: Ubuntu2004

init:
  - git config --global core.autocrlf true

install:
  - nvm use 14
  - node --version
  - cd puppeteer
  - npm install
  - cd $APPVEYOR_BUILD_FOLDER
  - cd ..
  - mkdir -p SCTEST
  - cd SCTEST
  - git clone https://github.com/sproutcore/build-tools sproutcore
  - cd sproutcore
  - npm install
  - cd ..
  - sproutcore/bin/sproutcore init master
  - cd master
  - mkdir -p frameworks
  - cd frameworks
  - ln -s $APPVEYOR_BUILD_FOLDER sproutcore
  - ../sproutcore/bin/sproutcore serve --local-only=true --port=4020 --include-tests --disable-bt-feedback &
  - cd $APPVEYOR_BUILD_FOLDER
  - sleep 15 # give sc-server some time to start

build: off

test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  - node puppeteer/run_tests.js --no-experimental --exclude-targets=/sproutcore/greenhouse