# ==========================================================================
# Project:   SproutCore - Web Application
# License:   Licensed under MIT license (see license.js)
# ==========================================================================

# The configuration for this framework.
config :web_application,

  # Bundled frameworks within :web_application.
  :required => [:client_data_store, :app_statechart]
