# ==========================================================================
# Project:   SproutCore - Web Application
# License:   Licensed under MIT license (see license.js)
# ==========================================================================

# The configuration for this framework.
config :core_application,

  # Required other frameworks within SproutCore.
  :required => [:runtime]
