// SproutCore ViewBuilder Design Format v1.0
// WARNING: This file is automatically generated.  DO NOT EDIT.  Changes you
// make to this file will be lost.
Greenhouse.TestPage = SC.Page.design({
  mainView: SC.View.design({
    childViews: [SC.ButtonView.design({
      layout: {
        "width": 100,
        "height": 24,
        "top": 444,
        "left": 685
      },
      title: "dork",
      isDefault: YES
    })]
  }),
  myView: SC.View.design({
    childViews: [SC.ButtonView.design({
      layout: {
        "width": 100,
        "height": 24,
        "top": 208,
        "left": 49
      }
    }), SC.ButtonView.design({
      layout: {
        "width": 100,
        "height": 24,
        "top": 58,
        "left": 83
      }
    })]
  }),
  someView: SC.View.design({}),
  myC: SC.ObjectController.design({}),
  pageName: "Greenhouse.TestPage"
});
